[versions]
agp = "8.13.1"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
room_version = "2.8.3"
ksp_version = "2.0.21-1.0.27"
nav_version = "2.9.6"
icon_version = "1.9.4"
lifecycleLivedataKtx = "2.9.4"
workRuntimeKtx = "2.11.0"
materialIcon = "1.5.4"
junitExt = "1.1.5"
espresso = "3.5.1"
mockito = "5.3.1"
mockitoKotlin = "5.1.0"
archCoreTesting = "2.2.0"
coroutinesTest = "1.7.3"
turbine = "1.0.0"
roomTesting = "2.6.1"
junitKtx = "1.3.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
#androidx-compose-icon = { group = "androidx.compose.material", name = "material-icons-core" , version.ref = "icon_version" }
room = { group = "androidx.room", name = "room-runtime" , version.ref = "room_version"}
room-compiler = { group = "androidx.room", name = "room-compiler" , version.ref = "room_version"}
room-ktx = { group = "androidx.room", name = "room-ktx" , version.ref = "room_version"}
navigation = { group = "androidx.navigation", name = "navigation-compose" , version.ref = "nav_version"}
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
material-icon = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIcon" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
androidx-arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "archCoreTesting" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "roomTesting" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = {id = "com.google.devtools.ksp", version.ref = "ksp_version" }

[bundles]
unit-testing = [
    "junit",
    "mockito-core",
    "mockito-kotlin",
    "androidx-arch-core-testing",
    "kotlinx-coroutines-test",
    "turbine"
]

instrumented-testing = [
    "androidx-junit",
    "androidx-room-testing"
]